name: Release and Homebrew Update

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build and Publish
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build release binary
        run: cargo build --release

      - name: Create release tarball
        run: |
          mkdir package
          cp target/release/meshstack package/
          tar -czf meshstack-macos-universal.tar.gz -C package meshstack

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: meshstack-macos-universal.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build and test
        run: cargo test

      - name: Publish to crates.io
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
        continue-on-error: true

      - name: Bump Homebrew formula
        uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: meshstack
          homebrew-tap: afstanton/homebrew-meshstack
        env:
          COMMITTER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
